version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: textalk/websocket
    versions:
    - 1.5.0
    - 1.5.1
    - 1.5.2
